#!/bin/bash
echo "Instalando...introduzca su contraseña"
sudo apt install qemu-kvm qemu figlet zenity
sudo apt install --no-install-recommends virtinst 
sudo adduser $USER kvm
chmod +x qmulite
sudo cp qmulite /usr/local/bin
echo "Listo ya puedes ejecutar QMULITE :D"