#!/bin/bash
echo "Instalando...introduzca su contraseña"
sudo apt install qemu-kvm qemu virtinst figlet zenity
sudo adduser $USER kvm
chmod +x qmulite
sudo cp qmulite /usr/local/bin
echo "Listo ya puedes ejecutar QMULITE :D"